name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Apply patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build
        run: ./gradlew createMojmapPaperclipJar --stacktrace
      - name: Upload Server Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Server
          path: octopus-server/build/libs
      - name: Upload API Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: API
          path: octopus-api/build/libs
